### ISSUE TITLE
Move app onto workingwomenadvocates.org

### ISSUE THREAD

**Issue by rachel-rocks-at-ruby** [Working-Women-Advocates/working-women-advocates#23]

**Comment by rachel-rocks-at-ruby** [comment]
how to transfer domain on HostMonster https://my.hostmonster.com/cgi/help/645

**Comment by rachel-rocks-at-ruby** [comment]
Need to be clear on how to migrate email addresses and minimize downtime

**Comment by bethqiang** [comment]
Done!! 😁
